export const DEFAULT_PORT = 7001;

export const DEFAULT_KAKAO_CHATBOT_ID = 'KAKAO_CHATBOT_ID'

export const DEFAULT_KAKAO_CHATBOT_BLOCK_ID_INQUIRE_ASSET
= 'KAKAO_CHATBOT_BLOCK_ID_INQUIRE_ASSET';
export const DEFAULT_KAKAO_CHATBOT_BLOCK_ID_REPORT
= 'KAKAO_CHATBOT_BLOCK_ID_REPORT';
export const DEFAULT_KAKAO_CHATBOT_BLOCK_ID_SUBSCRIBE_ASSET
= 'KAKAO_CHATBOT_BLOCK_ID_SUBSCRIBE_ASSET';
export const DEFAULT_KAKAO_CHATBOT_BLOCK_ID_CANCEL_ASSET_SUBSCRIPTION
= 'KAKAO_CHATBOT_BLOCK_ID_CANCEL_ASSET_SUBSCRIPTION';

export const DEFAULT_MARKET_API_TIMEOUT = 10000;

export const DEFAULT_REDIS_URL = 'redis://localhost:6379';

export const DEFAULT_THRESHOLD_PRICE_COUNT = 1;

export const DEFAULT_PM2_LISTEN_TIMEOUT = 60000;

export const DEFAULT_TEMP_KEY = 'TEMP_KEY';