export const DEFAULT_PORT = 6001;

export const DEFAULT_CHILD_API_TIMEOUT = 30000;
export const DEFAULT_CHILD_API_WORKERS = 1;
export const DEFAULT_CHILD_API_CONCURRENCY = 50;

export const DEFAULT_PM2_LISTEN_TIMEOUT = 60000;

export const DEFAULT_PRODUCT_API_TIMEOUT = 10000;

export const DEFAULT_TEMP_KEY = 'TEMP_KEY';

export const DEFAULT_THROTTLE_TTL_SHORT = 3000;
export const DEFAULT_THROTTLE_LIMIT_SHORT = 5;

export const DEFAULT_THROTTLE_TTL_LONG = 60000;
export const DEFAULT_THROTTLE_LIMIT_LONG = 20;