export const DEFAULT_PORT = 6001;

export const DEFAULT_CHILD_API_TIMEOUT = 60000;
export const DEFAULT_CHILD_API_WORKERS = 1;
export const DEFAULT_CHILD_API_CONCURRENCY = 250;
export const DEFAULT_CHILD_API_THREADPOOL_WORKERS = 5000;

export const DEFAULT_PM2_LISTEN_TIMEOUT = 60000;

export const DEFAULT_PRODUCT_API_TIMEOUT = 10000;

export const DEFAULT_TEMP_KEY = 'TEMP_KEY';