export const INMEMORY_STORE_SERVICE = "INMEMORY_STORE_SERVICE";
export const INMEMORY_STORE_BACKUP_SERVICE = "INMEMORY_STORE_BACKUP_SERVICE";
export const INMEMORY_SCHEMA_REPOSITORY_SUFFIX = "REPOSITORY";