export const INMEMORY_STORE_SERVICE_TOKEN = "INMEMORY_STORE_SERVICE";
export const INMEMORY_STORE_BACKUP_SERVICE_TOKEN = "INMEMORY_STORE_BACKUP_SERVICE";
export const INMEMORY_SCHEMA_REPOSITORY_TOKEN_SUFFIX = "REPOSITORY";