FROM keymetrics/pm2:16-alpine

RUN apk update \
&& apk add --no-cache curl

RUN npm install -g npm@8.19.3 \
&& npm config set fetch-retry-maxtimeout 1200000 \
&& npm config set fetch-timeout 1200000

ENV NODE_OPTIONS="--max-old-space-size=600"

# Todo: 여기서 COPY 하면, env 나 cert 변경시 market, product 빌드에서 캐시 이용 안하면서 느려짐
COPY ./env /home/node/app
COPY ./cert /home/node/app