version: "3"

services:
  market-child:
    container_name: pfa-market-child
    image: pfa-market-child:latest
    networks:
      - default
    ports:
      - "8001:8001"
    restart: always
    profiles:
      - pfa
      - market
  
  market:
    container_name: pfa-market
    image: pfa-market:latest
    networks:
      - default
      - market
    ports:
      - "6001:6001"
    environment:
      - RACK_ENV=development
    depends_on:
      market-mongo:
        condition: service_started
        restart: false
      market-postgres:
        condition: service_started
        restart: false
      market-child:
        condition: service_started
        restart: false
    restart: always
    profiles:
      - pfa
      - market

  market-mongo:
    container_name: pfa-market-mongo
    image: mongo:latest
    networks:
      - market
    restart: always
    profiles:
      - pfa
      - market
  
  market-postgres:
    container_name: pfa-market-postgres
    image: postgres:latest
    networks:
      - market
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    profiles:
      - pfa
      - market
  
  product:
    container_name: pfa-product
    image: pfa-product:latest
    networks:
      - default
      - product
    ports:
      - "7001:7001"
    depends_on:
      product-redis:
        condition: service_started
        restart: false
      market:
        condition: service_started
        restart: false
    restart: always
    profiles:
      - pfa
      - product

  product-redis:
    container_name: pfa-product-redis
    image: pfa-product-redis:latest
    networks:
      - product
    restart: always
    profiles:
      - pfa
      - product

  nginx:
    container_name: pfa-nginx
    image: pfa-nginx:latest
    networks:
      - default
    ports:
      - "80:80"
    depends_on:
      product:
        condition: service_started
        restart: false
      market:
        condition: service_started
        restart: false
      market-child:
        condition: service_started
        restart: false
    restart: always
    profiles:
      - pfa

networks:
  default:
    name: pfa-network
    driver: bridge
  product:
    name: pfa-product-network
    driver: bridge
  market:
    name: pfa-market-network
    driver: bridge
