export enum AppEnvKey {
  PORT = 'PORT',
  DOCKER_ENV = 'RACK_ENV',
  MAINTENANCE = 'MAINTENANCE_APP',
}

export enum FinancialAssetEnvKey {
  RENEWAL_THRESHOLD = 'FINANCIAL_ASSET_RENEWAL_THRESHOLD'
}

export enum KakaoChatbotEnvKey {
  ID = 'KAKAO_CHATBOT_ID',
  BLOCK_ID_INQUIRE_ASSET = 'KAKAO_CHATBOT_BLOCK_ID_INQUIRE_ASSET',
  BLOCK_ID_REPORT = 'KAKAO_CHATBOT_BLOCK_ID_REPORT',
  BLOCK_ID_SUBSCRIBE_ASSET = 'KAKAO_CHATBOT_BLOCK_ID_SUBSCRIBE_ASSET',
  BLOCK_ID_CANCEL_ASSET_SUBSCRIPTION = 'KAKAO_CHATBOT_BLOCK_ID_CANCEL_ASSET_SUBSCRIPTION',
  BLOCK_ID_INQUIRE_SUBSCRIBED_ASSET = "KAKAO_CHATBOT_BLOCK_ID_INQUIRE_SUBSCRIBED_ASSET",
  BLOCK_ID_INQUIRE_ASSET_NO_INPUT = "KAKAO_CHATBOT_BLOCK_ID_INQUIRE_ASSET_NO_INPUT",
  BLOCK_ID_HELP = "KAKAO_CHATBOT_BLOCK_ID_HELP",
  BLOCK_ID_INTRODUCE = "KAKAO_CHATBOT_BLOCK_ID_INTRODUCE",
  BLOCK_ID_SPONSOR = "KAKAO_CHATBOT_BLOCK_ID_SPONSOR",

  ID_STOREBOT_ORDER = 'KAKAO_CHATBOT_ID_STOREBOT_ORDER',
  BLOCK_ID_SCHEDULE_LAUNCH_ALARM = 'KAKAO_CHATBOT_BLOCK_ID_SCHEDULE_LAUNCH_ALARM',

  // survey test
  ID_STOREBOT = 'KAKAO_CHATBOT_ID_STOREBOT',
  BLOCK_ID_SURVEY_START = 'KAKAO_CHATBOT_BLOCK_ID_SURVEY_START',
  BLOCK_ID_SURVEY_ANSWER = 'KAKAO_CHATBOT_BLOCK_ID_SURVEY_ANSWER',
  BLOCK_ID_SURVEY_GET_EVENT_SERIAL = "KAKAO_CHATBOT_BLOCK_ID_SURVEY_GET_EVENT_SERIAL",

  URL_TAEYCOFFEROASTERS_COOKIES_IMAGE="URL_TAEYCOFFEROASTERS_COOKIES_IMAGE",
}

export enum MarketApiEnvKey {
  BASE_URL = 'MARKET_API_BASE_URL',
  TIMEOUT = 'MARKET_API_TIMEOUT',
}

export enum Pm2EnvKey {
  NAME = 'PM2_NAME',
  LISTEN_TIMEOUT = 'listen_timeout',
}

export enum PostgresEnvKey {
  HOST = 'PG_HOST',
  USERNAME = 'PG_USERNAME',
  PASSWORD = 'PG_PASSWORD',
  DATABASE = 'PG_DATABASE',
}

export enum RedisEnvKey {
  URL = 'REDIS_URL',
}

export enum TempEnvKey {
  KEY = 'TEMP_KEY',
}

export enum ThrottleEnvKey {
  TTL_GLOBAL_SHORT = 'THROTTLE_TTL_GLOBAL_SHORT',
  LIMIT_GLOBAL_SHORT = 'THROTTLE_LIMIT_GLOBAL_SHORT',

  TTL_GLOBAL_MEDIUM = 'THROTTLE_TTL_GLOBAL_MEDIUM',
  LIMIT_GLOBAL_MEDIUM = 'THROTTLE_LIMIT_GLOBAL_MEDIUM',

  TTL_GLOBAL_LONG = 'THROTTLE_TTL_GLOBAL_LONG',
  LIMIT_GLOBAL_LONG = 'THROTTLE_LIMIT_GLOBAL_LONG',

  TTL_GLOBAL_CUT = 'THROTTLE_TTL_GLOBAL_CUT',
  LIMIT_GLOBAL_CUT = 'THROTTLE_LIMIT_GLOBAL_CUT',

  TTL_KAKAO_CHATBOT_SHORT = 'THROTTLE_TTL_KAKAO_CHATBOT_SHORT',
  LIMIT_KAKAO_CHATBOT_SHORT = 'THROTTLE_LIMIT_KAKAO_CHATBOT_SHORT',

  TTL_KAKAO_CHATBOT_LONG = 'THROTTLE_TTL_KAKAO_CHATBOT_LONG',
  LIMIT_KAKAO_CHATBOT_LONG = 'THROTTLE_LIMIT_KAKAO_CHATBOT_LONG',
}

export enum OpenAIEnvKey {
  API_KEY = 'OPENAI_API_KEY',
}