export enum AppEnvKey {
  PORT = 'PORT',
  DOCKER_ENV = 'RACK_ENV'
}

export enum FinancialAssetEnvKey {
  RENEWAL_THRESHOLD = 'FINANCIAL_ASSET_RENEWAL_THRESHOLD'
}

export enum KakaoChatbotEnvKey {
  ID = 'KAKAO_CHATBOT_ID',
  BLOCK_ID_INQUIRE_ASSET = 'KAKAO_CHATBOT_BLOCK_ID_INQUIRE_ASSET',
  BLOCK_ID_REPORT = 'KAKAO_CHATBOT_BLOCK_ID_REPORT',
  BLOCK_ID_SUBSCRIBE_ASSET = 'KAKAO_CHATBOT_BLOCK_ID_SUBSCRIBE_ASSET',
  BLOCK_ID_CANCEL_ASSET_SUBSCRIPTION = 'KAKAO_CHATBOT_BLOCK_ID_CANCEL_ASSET_SUBSCRIPTION',

  // survey test
  ID_STOREBOT = 'KAKAO_CHATBOT_ID_STOREBOT',
  BLOCK_ID_SURVEY_START = 'KAKAO_CHATBOT_BLOCK_ID_SURVEY_START',
  BLOCK_ID_SURVEY_ENTER = 'KAKAO_CHATBOT_BLOCK_ID_SURVEY_ENTER',
  BLOCK_ID_SURVEY_ANSWER = 'KAKAO_CHATBOT_BLOCK_ID_SURVEY_ANSWER',
}

export enum MarketApiEnvKey {
  BASE_URL = 'MARKET_API_BASE_URL',
  TIMEOUT = 'MARKET_API_TIMEOUT',
}

export enum Pm2EnvKey {
  NAME = 'PM2_NAME',
  LISTEN_TIMEOUT = 'listen_timeout',
}

export enum PostgresEnvKey {
  HOST = 'PG_HOST',
  USERNAME = 'PG_USERNAME',
  PASSWORD = 'PG_PASSWORD',
  DATABASE = 'PG_DATABASE',
}

export enum RedisEnvKey {
  URL = 'REDIS_URL',
}

export enum TempEnvKey {
  KEY = 'TEMP_KEY',
}

export enum ThrottleEnvKey {
  TTL_GLOBAL_SHORT = 'THROTTLE_TTL_GLOBAL_SHORT',
  LIMIT_GLOBAL_SHORT = 'THROTTLE_LIMIT_GLOBAL_SHORT',

  TTL_GLOBAL_LONG = 'THROTTLE_TTL_GLOBAL_LONG',
  LIMIT_GLOBAL_LONG = 'THROTTLE_LIMIT_GLOBAL_LONG',

  TTL_KAKAO_CHATBOT_SHORT = 'THROTTLE_TTL_KAKAO_CHATBOT_SHORT',
  LIMIT_KAKAO_CHATBOT_SHORT = 'THROTTLE_LIMIT_KAKAO_CHATBOT_SHORT',

  TTL_KAKAO_CHATBOT_LONG = 'THROTTLE_TTL_KAKAO_CHATBOT_LONG',
  LIMIT_KAKAO_CHATBOT_LONG = 'THROTTLE_LIMIT_KAKAO_CHATBOT_LONG',
}
