# /etc/nginx/nginx.conf

user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  8192;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format main
            'ts=$msec|raddr=$remote_addr|srv=$server_name|'
            'm=$request_method|uri=$request_uri|proto=$server_protocol|'
            'sc=$status|bytes=$body_bytes_sent|'
            'rt=$request_time|uct=$upstream_connect_time|uht=$upstream_header_time|urt=$upstream_response_time|'
            'uaddr=$upstream_addr|ustatus=$upstream_status|'
            'req_len=$request_length|resp_len=$bytes_sent|'
            'conn=$connection|creq=$connection_requests|'
            'ua="$http_user_agent"|xff="$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  60;
    keepalive_requests 1000;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
