version: "3"

services:
  redis:
    container_name: pfa-product-intergration-test-redis
    image: redis:7.2-rc2-alpine3.18
    ports:
      - "6379:6379"
    expose:
      - "6379"
    restart: always
    profiles:
      - test