import exchange_calendars as xcals
import json
from datetime import datetime

t = xcals.get_calendar("XNYS")
k = xcals.get_calendar("XKRX")
j = xcals.get_calendar("XTKS")
print(datetime.utcnow())
print(t.name)
print(t.previous_open(datetime.utcnow()))
print(t.previous_close(datetime.utcnow()))
print(t.next_open(datetime.utcnow()))
print(t.next_close(datetime.utcnow()))
print(t.schedule.index[-1])
print(t.schedule.index[-2])
print(t.schedule.index[-3])
print(k.name)
print(k.previous_open(datetime.utcnow()))
print(k.previous_close(datetime.utcnow()))
print(k.next_open(datetime.utcnow()))
print(k.next_close(datetime.utcnow()))
print(k.schedule.index[-1])
print(k.schedule.index[-2])
print(k.schedule.index[-3])
print(j.name)
print(j.previous_open(datetime.utcnow()))
print(j.previous_close(datetime.utcnow()))
print(j.next_open(datetime.utcnow()))
print(j.next_close(datetime.utcnow()))
print(j.schedule.index[-1])
print(j.schedule.index[-2])
print(j.schedule.index[-3])