export enum EnvKey {
    PORT = 'PORT',
    
    // .env
    MONGODB_NAME = 'MONGO_database',
    MONGODB_URL = 'MONGO_URL',
    MONGODB_QUERY = 'MONGO_Query',
    CHILD_API_TIMEOUT = 'CHILD_API_TIMEOUT',
    CHILD_WORKERS = 'CHILD_WORKERS',
    CHILD_CONCURRENCY = 'CHILD_CONCURRENCY',
    PRODUCT_API_TIMEOUT = 'PRODUCT_API_TIMEOUT',
    TEMP_KEY = 'TEMP_KEY',
    PG_HOST = 'PG_HOST',
    PG_USERNAME = 'PG_USERNAME',
    PG_PASSWORD = 'PG_PASSWORD',
    PG_DATABASE = 'PG_DATABASE',

    // pm2
    PM2_NAME = 'PM2_NAME',
    PM2_LISTEN_TIMEOUT = 'listen_timeout',

    // docker
    DOCKER_CHILD_API_BASE_URL = 'CHILD_API_BASE_URL',
    DOCKER_PRODUCT_API_BASE_URL = 'PRODUCT_API_BASE_URL',
    DOCKER_ENV = 'RACK_ENV',

    // load
    MONGODB_URI = 'MONGODB_URI'
}