export const REDIS_CLIENT_TOKEN = "REDIS_CLIENT_TOKEN";
export const REIDS_SCHEMA_SERVICE_TOKEN_SUFFIX = "REIDS_SCHEMA_SERVICE_TOKEN_SUFFIX";
export const REDIS_REPOSITORY_TOKEN_SUFFIX = "REDIS_REPOSITORY_TOKEN_SUFFIX";