export const EXCHANGE_PROVIDER_TOKEN_SUFFIX = "EXCHANGE_PROVIDER";
export const EXCHANGE_SESSION_PROVIDER_TOKEN_SUFFIX = "EXCHANGE_SESSION_PROVIDER";
export const EXCHANGE_CONFIG_PROVIDER_TOKEN_SUFFIX = "EXCHANGE_CONFIG_PROVIDER";